name: Build APK

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Choose the Python version you need

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git wget unzip

    - name: Install buildozer
      run: |
        python3 -m pip install --upgrade buildozer

    - name: Build APK
      run: |
        buildozer -v -o /buildozer.spec android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: ./bin/*.apk
