name: Build APK

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
  uses: actions/setup-python@v2
  with:
    python-version: 3.8  # Choose a different Python version


            - name: Install dependencies
        run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git wget unzip python3-distutils
         - name: Install distutils
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-distutils
     

    - name: Install buildozer
      run: |
        python3 -m pip install --upgrade buildozer

    - name: Build APK
      run: |
        cd .github/workflows
        buildozer -v -o .github/workflows/buildozer.spec android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: ./.github/workflows/bin/*.apk
